nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.1.cjs

enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
